### ISSUE TITLE
IPM Parser Help

### ISSUE THREAD

**Issue by kbjan26** [shakshin/isoparser#2]
Hello Shakshin,

We are trying to use your parser with customization to parse mastercard data. However we are facing the below issue while reading data from input stream.

[error] [Utils]: Can not parse embedded length for field: DE 43
[error] [IsoMessage]: Field read error: Can not parse embedded length. Field: DE 43; For input string: "\1"
[error] [IsoMessage]: Message can not be parsed: ISO field can not be read from stream: Can not parse embedded length. Field: DE 43; For input string: "\1"

With your code as is it works all good

**Comment by kbjan26** [comment]
Hey Mate,

I have a question to ask. How significant IPMProbe.Java in the parser. Can
we try living without it ?

I tried but parsing is failing. We are having issues surviving with
FileInputStream.

We need this parsing code to source contents from S3 bucket and parse the
IPM file.

We will have tough time in creating a filestream/getting absolute file path
as we can see it’s used in IPMProbe.java

Regards,
Balaji K

**Comment by shakshin** [comment]
Hi!
IPMProbe is optional. 
If you use this as an standalone utility, you should just specify exact layout and encoding to prevent invocation of IPMProbe.

**Comment by shakshin** [comment]
Hey friend!
Could please provide description of the error which you've got using the IPMProbe?

**Comment by kbjan26** [comment]
Hey Mate,

It’s again not an issue with your parser. It was our issue while supplying
the data. Fixed it now.

Thanks for your prompt follow up. Please support us in case if I come back
with questions.


Regards,
Balaji K
