### ISSUE TITLE
Byte[] heapmemory issue

### ISSUE THREAD

**Issue by kbjan26** [shakshin/isoparser#4]
Hey Shakshin,

The byte[] used in several areas in the code is eating up the heap-memory and its not coming down at all once the process is over.

How do we deal about it ? Tried initialising variables to NULL at several places to make the heap memory eligible for garbage collection. Is it the right approach that is being taken ?

**Comment by shakshin** [comment]
Hi!
Yes. Setting reference to null will cause GC to clean up unreferenced objects from heap.

**Comment by kbjan26** [comment]
Thanks for your response Shakshin.

Another question on the below issue we are getting while parsing IPM file

2022-04-07 11:37:00.961 ERROR 50174 --- [nio-8090-exec-1] com.cards.parser.IsoMessage              : IsoMessage :Field read error: 
java.io.IOException: Can not parse embedded length. Field: DE 48; For input string: "2@@"

Is it something expected behavior from parser while parsing the elements ? The processing stops due to this error

**Comment by shakshin** [comment]
This case is expected. The problem is in ISO data. Field DE48 should have embedded length - 3 digits. AS you can see, parser could not parse this bytes as a number. And then, as we don't know how long the field is - we can not know where to find next field.

**Comment by kbjan26** [comment]
One more query to ask , when the parser is trying to decode DE 48 it has special characters - "ARA���������������������"

pds0171: 'ARA���������������������'
pds0177: 'YY'
pds0178: 'ARA���������������������'

What could be the reason for the special characters in the output from parser ?

**Comment by shakshin** [comment]
Hi!
This could be in case when your file contains some national characters. Mastercard IPM specification describes: file could contain only ASCII or EBCDIC characters. No national symbols are allowed. So we don't  expect them.
